# Generated by Django 5.1.2 on 2024-10-15 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('departement', models.CharField(choices=[('RESEAU', 'Direction Réseau'), ('COMMERCE', 'Direction commerce général'), ('FINANCE', 'Direction financière')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('reference', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(choices=[('ATTESTATION_TRAVAIL', 'Attestation de travail'), ('ATTESTATION_CONGES', 'Attestation de congés'), ('ORDRE_MISSION', 'Ordre de mission'), ('ACCORD_TRIPARTITE', 'Accord tripartite')], max_length=50)),
                ('motif', models.TextField(blank=True, null=True)),
                ('periode_conge_debut', models.DateField(blank=True, null=True)),
                ('periode_conge_fin', models.DateField(blank=True, null=True)),
                ('date_reprise', models.DateField(blank=True, null=True)),
                ('lieu_mission', models.CharField(blank=True, max_length=100, null=True)),
                ('objet_mission', models.CharField(blank=True, max_length=200, null=True)),
                ('lettre_invitation', models.FileField(blank=True, null=True, upload_to='lettres/')),
                ('billet', models.FileField(blank=True, null=True, upload_to='billets/')),
                ('banque', models.CharField(blank=True, choices=[('BANQUE_ATLANTIQUE', 'BANQUE ATLANTIQUE TOGO'), ('BIA_TOGO', 'BANQUE INTERNATIONALE POUR L’AFRIQUE AU TOGO'), ('SUNU_BANK', 'SUNU BANK'), ('BSIC', 'BANQUE SAHELO-SAHARIENNE POUR L’INVESTISSEMENT ET LE COMMERCE'), ('IB_BANK', 'INTERNATIONAL BUSINESS BANK TOGO'), ('ECOBANK', 'ECOBANK - TOGO'), ('ORABANK', 'ORABANK TOGO'), ('SIAB', 'SOCIETE INTERAFRICAINE DE BANQUE'), ('UTB', 'UNION TOGOLAISE DE BANQUE'), ('BOA', 'BANK OF AFRICA TOGO'), ('CBI', 'CORIS BANK INTERNATIONAL- TOGO'), ('AUTRE', 'Autre (Précisez)')], max_length=50, null=True)),
                ('tableau_amortissement', models.FileField(blank=True, null=True, upload_to='amortissements/')),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.collaborateur')),
            ],
        ),
    ]
