# Generated by Django 5.1.2 on 2024-10-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='collaborateur',
        ),
        migrations.DeleteModel(
            name='Collaborateur',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
    ]
