# Generated by Django 5.1.2 on 2024-11-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='banque',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='collaborateur',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='document',
        ),
        migrations.DeleteModel(
            name='Banque',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='Collaborateur',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
