# Generated by Django 5.1.2 on 2024-11-12 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0004_remove_demande_banque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('departement', models.CharField(choices=[('Direction Réseau', 'Direction Réseau'), ('Direction Commerce Général', 'Direction Commerce Général'), ('Direction Financière', 'Direction Financière')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Attestation de Travail', 'Attestation de Travail'), ('Attestation de Congés', 'Attestation de Congés'), ('Ordre de Mission', 'Ordre de Mission'), ('Accord Tripartite', 'Accord Tripartite')], max_length=100)),
                ('motif', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resume_date', models.DateField(blank=True, null=True)),
                ('mission_location', models.CharField(blank=True, max_length=255, null=True)),
                ('mission_object', models.TextField(blank=True, null=True)),
                ('invitation_letter', models.FileField(blank=True, null=True, upload_to='invitations/')),
                ('ticket_copy', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('bank_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('amortization_table', models.FileField(blank=True, null=True, upload_to='amortizations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandes.employee')),
            ],
        ),
    ]
