# Generated by Django 5.1.2 on 2024-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdocument',
            name='employee',
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='email',
            field=models.EmailField(default='total@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='nom',
            field=models.CharField(default='Joe', max_length=100),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='prenoms',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='reference',
            field=models.CharField(default='J12', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='document_type',
            field=models.CharField(choices=[('attestation_travail', 'Attestation de Travail'), ('attestation_conges', 'Attestation de Congés'), ('ordre_mission', 'Ordre de Mission'), ('accord_tripartite', 'Accord Tripartite')], max_length=100),
        ),
    ]
