# Generated by Django 5.1.2 on 2024-11-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0006_remove_requestdocument_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_cours', max_length=20),
        ),
    ]
