# Generated by Django 5.1.2 on 2024-12-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0007_requestdocument_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='departement',
            field=models.CharField(choices=[('direction_reseau', 'Direction Réseau'), ('direction_financiere', 'Direction Financière'), ('direction_commerciale', 'Direction Commerciale'), ('direction_hseq', 'Direction HSEQ'), ('direction_rhj', 'Direction des Ressources Humaines et Juridique')], default='direction_financière', max_length=100),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='poste',
            field=models.CharField(default='Assistant IT', max_length=100),
        ),
    ]
