# Generated by Django 5.1.2 on 2024-12-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0008_requestdocument_departement_requestdocument_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='monthly_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='repayment_duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='repayment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestdocument',
            name='document_type',
            field=models.CharField(choices=[('attestation_travail', 'Attestation de Travail'), ('attestation_conges', 'Attestation de Congés'), ('ordre_mission', 'Ordre de Mission'), ('accord_tripartite', 'Accord Tripartite'), ('pret_depannage', 'Prêt Dépannage')], max_length=100),
        ),
    ]
