# Generated by Django 5.1.2 on 2024-12-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0009_requestdocument_loan_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
